// ============================================================
// lib/data.ts – Static seed data (replace with Supabase later)
// ============================================================
import type { Course, PricingPlan, Testimonial, VocabTopic, VocabWord } from "@/types";

export const COURSES: Course[] = [
  {
    id: "daily-conversation",
    title: "Giao tiếp tiếng Anh hàng ngày",
    description: "Tự tin giao tiếp trong mọi tình huống: mua sắm, du lịch, công việc, kết bạn quốc tế.",
    category: "conversation",
    level: "elementary",
    total_lessons: 48,
    thumbnail_emoji: "💬",
    banner_gradient: "linear-gradient(135deg,#EBF4FF,#BFDBFE)",
    is_free: true,
    tags: ["Phổ biến nhất", "Giao tiếp"],
  },
  {
    id: "ielts-mastery",
    title: "Luyện thi IELTS từ 0 → 7.5+",
    description: "Lộ trình đầy đủ 4 kỹ năng: Listening, Reading, Writing, Speaking với đề thi cập nhật.",
    category: "ielts",
    level: "intermediate",
    total_lessons: 120,
    thumbnail_emoji: "🏆",
    banner_gradient: "linear-gradient(135deg,#FEF3C7,#FDE68A)",
    is_free: false,
    tags: ["IELTS", "Bán chạy"],
  },
  {
    id: "toeic-900",
    title: "Luyện thi TOEIC 600 → 900+",
    description: "Chinh phục TOEIC với chiến lược làm bài hiệu quả, 500+ đề luyện.",
    category: "toeic",
    level: "intermediate",
    total_lessons: 80,
    thumbnail_emoji: "📊",
    banner_gradient: "linear-gradient(135deg,#F0FFF4,#BBF7D0)",
    is_free: false,
    tags: ["TOEIC"],
  },
  {
    id: "business-english",
    title: "Tiếng Anh thương mại",
    description: "Email công việc, thuyết trình, đàm phán, họp online – chuyên nghiệp trong công sở.",
    category: "business",
    level: "upper-intermediate",
    total_lessons: 60,
    thumbnail_emoji: "💼",
    banner_gradient: "linear-gradient(135deg,#F5F0FF,#DDD6FE)",
    is_free: false,
    tags: ["Business"],
  },
  {
    id: "absolute-beginner",
    title: "Tiếng Anh từ A–Z cho người mới",
    description: "Bắt đầu từ con số 0: bảng chữ cái, phát âm, ngữ pháp cơ bản, 1000 từ vựng thiết yếu.",
    category: "beginner",
    level: "beginner",
    total_lessons: 35,
    thumbnail_emoji: "🌱",
    banner_gradient: "linear-gradient(135deg,#FFF0F3,#FFD6E0)",
    is_free: true,
    tags: ["Người mới", "Miễn phí"],
  },
  {
    id: "travel-english",
    title: "Tiếng Anh du lịch thực chiến",
    description: "Nói chuyện tự tin khi du lịch nước ngoài: đặt phòng, chỉ đường, mua sắm, khẩn cấp.",
    category: "travel",
    level: "elementary",
    total_lessons: 28,
    thumbnail_emoji: "✈️",
    banner_gradient: "linear-gradient(135deg,#E0F7FA,#B2EBF2)",
    is_free: true,
    tags: ["Chủ đề"],
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Miễn phí",
    price_vnd: 0,
    duration_months: 0,
    icon: "🆓",
    description: "Thử nghiệm không giới hạn thời gian",
    features: [
      "5 bài học giao tiếp cơ bản",
      "100 flashcard từ vựng",
      "Bài test trình độ miễn phí",
      "Theo dõi streak 7 ngày",
    ],
    is_popular: false,
  },
  {
    id: "pro-monthly",
    name: "Pro Tháng",
    price_vnd: 99000,
    duration_months: 1,
    icon: "⭐",
    description: "Học không giới hạn, tiến bộ nhanh nhất",
    features: [
      "Truy cập toàn bộ khóa học",
      "5,000+ flashcard từ vựng",
      "Luyện tập phát âm AI",
      "Bài tập nghe & ghi âm",
      "Streak không giới hạn",
      "Chứng chỉ hoàn thành",
    ],
    is_popular: true,
    badge: "🔥 Được chọn nhiều nhất",
  },
  {
    id: "pro-quarterly",
    name: "Pro 3 Tháng",
    price_vnd: 199000,
    original_price_vnd: 297000,
    duration_months: 3,
    icon: "💎",
    description: "Tiết kiệm nhất – dành cho học viên nghiêm túc",
    features: [
      "Tất cả tính năng Pro Tháng",
      "Ưu tiên hỗ trợ học viên",
      "Lộ trình cá nhân hóa AI",
      "IELTS mock test đầy đủ",
      "Tải bài học nghe offline",
    ],
    is_popular: false,
    badge: "💚 Tiết kiệm 33%",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Minh Anh",
    role: "Sinh viên ĐHBK, Hà Nội",
    avatar_initial: "M",
    avatar_gradient: "linear-gradient(135deg,#4A90E2,#2563EB)",
    text: "Mình đã học nhiều app nhưng SpeakNest là cái duy nhất mình duy trì được hơn 3 tháng. Giao diện đẹp, bài học dễ hiểu, giải thích tiếng Việt rất rõ ràng!",
    rating: 5,
  },
  {
    id: "2",
    name: "Thanh Tú",
    role: "Kỹ sư phần mềm, TP.HCM",
    avatar_initial: "T",
    avatar_gradient: "linear-gradient(135deg,#FF7043,#FF8C42)",
    text: "IELTS 7.0 sau 4 tháng học trên SpeakNest! Giá 99k/tháng mà chất lượng hơn trung tâm hàng triệu!",
    rating: 5,
    achievement: "IELTS 7.0",
  },
  {
    id: "3",
    name: "Hoàng Nam",
    role: "Nhân viên marketing, Đà Nẵng",
    avatar_initial: "H",
    avatar_gradient: "linear-gradient(135deg,#22C55E,#16A34A)",
    text: "Daily streak 120 ngày rồi! Flashcard thông minh giúp mình nhớ từ vựng cực nhanh. App đẹp, không bị rối mắt!",
    rating: 5,
    achievement: "120 ngày streak",
  },
];

export const VOCAB_TOPICS: VocabTopic[] = [
  { id: "food", name: "Ẩm thực", emoji: "🍜", word_count: 120, color: "#FEF3C7" },
  { id: "work", name: "Công việc", emoji: "💼", word_count: 200, color: "#EBF4FF" },
  { id: "health", name: "Y tế", emoji: "🏥", word_count: 150, color: "#FFF0F3" },
  { id: "travel", name: "Du lịch", emoji: "✈️", word_count: 180, color: "#E0F7FA" },
  { id: "academic", name: "Học thuật", emoji: "🎓", word_count: 250, color: "#F5F0FF" },
  { id: "family", name: "Gia đình", emoji: "🏠", word_count: 90, color: "#F0FFF4" },
  { id: "tech", name: "Công nghệ", emoji: "💻", word_count: 210, color: "#EBF4FF" },
  { id: "sports", name: "Thể thao", emoji: "⚽", word_count: 130, color: "#F0FFF4" },
  { id: "environment", name: "Môi trường", emoji: "🌍", word_count: 160, color: "#F0FFF4" },
  { id: "arts", name: "Nghệ thuật", emoji: "🎭", word_count: 100, color: "#F5F0FF" },
  { id: "finance", name: "Tài chính", emoji: "💰", word_count: 190, color: "#FEF3C7" },
  { id: "music", name: "Âm nhạc", emoji: "🎵", word_count: 80, color: "#FFF0F3" },
];

export const SAMPLE_FLASHCARDS: VocabWord[] = [
  { id: "1", topic_id: "sports", word: "Resilient", phonetic: "/rɪˈzɪliənt/", meaning_vi: "Kiên cường, có khả năng phục hồi", meaning_en: "Able to withstand or recover quickly from difficult conditions", example_sentence: "She is very resilient and always bounces back from failure.", level: "intermediate" },
  { id: "2", topic_id: "sports", word: "Dedication", phonetic: "/ˌdedɪˈkeɪʃn/", meaning_vi: "Sự cống hiến, tận tụy", meaning_en: "The quality of being committed to a task or purpose", example_sentence: "His dedication to learning English is truly admirable.", level: "intermediate" },
  { id: "3", topic_id: "sports", word: "Momentum", phonetic: "/məˈmentəm/", meaning_vi: "Đà tiến, xung lực", meaning_en: "The force or speed of an object in motion; impetus", example_sentence: "The team gained momentum after scoring the first goal.", level: "upper-intermediate" },
  { id: "4", topic_id: "sports", word: "Breakthrough", phonetic: "/ˈbreɪkθruː/", meaning_vi: "Bước đột phá", meaning_en: "A sudden, dramatic, and important discovery or development", example_sentence: "This is a major breakthrough in renewable energy.", level: "intermediate" },
  { id: "5", topic_id: "sports", word: "Perseverance", phonetic: "/ˌpɜːsɪˈvɪərəns/", meaning_vi: "Sự kiên trì, bền bỉ", meaning_en: "Continued effort to do or achieve something despite difficulty", example_sentence: "Perseverance is the key to mastering any language.", level: "upper-intermediate" },
];
